In [1]:
# import libraries
from utils.helpers import get_element, flatten_array

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, FunctionTransformer
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [2]:
# instatiate models and transformers
le = LabelEncoder()
clf = RandomForestClassifier()

In [3]:
# import data
data = pd.read_pickle("image_product.pkl")
data

id  \
0      7cdb36be-888e-4dc8-81ed-0b98e9e6a1c9   
1      369cbb17-75f4-43a3-9f67-cce821f0ed5e   
2      0f80c7cf-4c45-47df-a00d-0be822506933   
3      a5886822-a581-4ab3-9efc-959d1b58f3a8   
4      4a877282-182e-47f5-b4b6-24f0a88ab5fd   
...                                     ...   
11099  39026ffe-9994-4a0f-94a9-5123b3432065   
11100  2c353fc7-d78a-4b54-bea1-269708511a54   
11101  bf23f42a-9c32-4dff-ac5c-21ebe29b2a31   
11102  53b597af-093b-4492-8f15-cd89ea953c49   
11103  c9628f58-51b7-45c1-8035-144259302cd7   

                                            product_name  \
0      LUSH 1.6-1.8m Kentia palm 🌴 Indoor plant | in ...   
1      Genuine Xiaomi Redmi Power Bank 10000-mAh 2.4A...   
2      Mamas and Papas Kato 2 pushchair | in Swindon,...   
3      Air Jordan 4 Retro 'Taupe Haze' Size UK 6.5 - ...   
4      Sony PlayStation 3 Slim Console 320GB Black | ...   
...                                                  ...   
11099  CHEAPEST WARDROBE ==  ALINA BED ROOM SET with ...   
11100  Mobile Catering Trailer | in Northampton, Nort...   
11101   Cabinet handles | in East End, Glasgow | Gumtree   
11102  JINBERYL KIDS BACKPACK GIRLS SCHOOL BAG, FITS ...   
11103  NEW GREEN TREATED SOFTWOOD RAILWAY SLEEPERS, V...   

                                                category  \
0      Home & Garden / Garden & Patio / Garden Buildi...   
1      Phones, Mobile Phones & Telecoms / Mobile Phon...   
2                  Baby & Kids Stuff / Prams & Strollers   
3      Clothes, Footwear & Accessories / Men's Shoes ...   
4      Video Games & Consoles / Consoles / PS3 (Sony ...   
...                                                  ...   
11099  Home & Garden / Beds & Bedroom Furniture / War...   
11100  Office Furniture & Equipment / Restaurant & Ca...   
11101            DIY Tools & Materials / Doors & Windows   
11102  Clothes, Footwear & Accessories / Women's Acce...   
11103              DIY Tools & Materials / Wood & Timber   

                                     product_description    price  \
0      LUSH 1.6-1.8m Kentia palm 🌴 Indoor plant\r Lus...    75.00   
1      Xiaomi Redmi Power Bank 10000 mAh - WhiteMicro...    25.00   
2      Pushchair c/w rain cover. Small hole in hood s...    20.00   
3      Bought these couple weeks ago but I want to ge...   290.00   
4      Sony PlayStation 3 Slim Console 320GB Black. U...   140.00   
...                                                  ...      ...   
11099  More Information 0️⃣2️⃣0️⃣8️⃣0️⃣0️⃣4️⃣7️⃣7️⃣7️...   189.00   
11100  Great condition catering trailer - newly renov...  6950.00   
11101  10 x brushed steel cabinet handles plus 6 x hi...    10.00   
11102  SOLD OUT ITEM ON AMAZON - 28 AVAILABLE\r BRAND...    14.99   
11103  NEW GREEN TREATED SOFTWOOD RAILWAY SLEEPERS, V...    28.00   

                            location create_time  \
0                 Kennington, London  2022-02-26   
1             Watford, Hertfordshire  2022-02-27   
2                 Swindon, Wiltshire  2022-02-26   
3        Kettering, Northamptonshire  2022-02-26   
4                 Twickenham, London  2022-02-28   
...                              ...         ...   
11099               Southall, London  2022-02-26   
11100  Northampton, Northamptonshire  2022-02-27   
11101              East End, Glasgow  2022-02-27   
11102              Bearsden, Glasgow  2022-02-27   
11103            Kings Lynn, Norfolk  2022-02-27   

                                             image_array  
0      [[[144, 120, 82], [145, 123, 86], [149, 131, 9...  
1      [[[125, 136, 132], [141, 150, 145], [145, 148,...  
2      [[[171, 169, 157], [163, 161, 149], [155, 153,...  
3      [[[179, 137, 121], [176, 139, 120], [172, 141,...  
4      [[[160, 164, 147], [152, 159, 141], [192, 199,...  
...                                                  ...  
11099  [[[248, 236, 196], [230, 218, 180], [226, 213,...  
11100  [[[157, 181, 155], [122, 146, 120], [106, 129,...  
11101  [[[181, 172, 165], [182, 173, 166], [185, 

In [4]:
# set feature matrix X and response vector y
X = pd.DataFrame(data.image_array)
y = le.fit_transform(
        data.category.str.split("/").apply(get_element, position=0))

# glance of the data before split
print("Feature Matrix\n", X.head())
print("Response Vector\n", y[0:5])

Feature Matrix
                                          image_array
0  [[[144, 120, 82], [145, 123, 86], [149, 131, 9...
1  [[[125, 136, 132], [141, 150, 145], [145, 148,...
2  [[[171, 169, 157], [163, 161, 149], [155, 153,...
3  [[[179, 137, 121], [176, 139, 120], [172, 141,...
4  [[[160, 164, 147], [152, 159, 141], [192, 199,...
Response Vector
 [ 6 10  1  2 12]


In [5]:
# split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=0)

print("Training input shape", X_train.shape)
print("Training target shape", y_train.shape)
print("Testing input shape", X_test.shape)
print("Testing target shape", y_test.shape)

Training input shape (7772, 1)
Training target shape (7772,)
Testing input shape (3332, 1)
Testing target shape (3332,)


In [6]:
data.image_array[0].flatten()

array([144, 120,  82, ...,   0,   0,   0], dtype=uint8)

In [40]:
def flatten_array(ser):
    new_arr = ser.iloc[0][0].flatten()
    for i in ser.values:
        new_arr = np.row_stack(i.flatten())
    return new_arr

In [41]:
aaa = X_train.head()
bbb = flatten_array(aaa.image_array)

In [43]:
bbb

array([[255],
       [255],
       [255],
       ...,
       [  4],
       [  4],
       [  4]], dtype=uint8)

In [36]:
sum(X_train.iloc[4].values[0].flatten() == bbb)

9408

In [133]:
print(aaa[0][0].shape)
print(aaa[1])

#print(X_train.values[0])

(56, 56, 3)
[array([[[20, 18, 21],
         [18, 16, 19],
         [18, 16, 19],
         ...,
         [23, 19, 16],
         [21, 17, 14],
         [22, 18, 15]],

        [[21, 19, 22],
         [19, 17, 20],
         [19, 17, 20],
         ...,
         [23, 19, 16],
         [19, 15, 12],
         [18, 14, 11]],

        [[17, 15, 18],
         [15, 13, 16],
         [17, 15, 18],
         ...,
         [26, 25, 23],
         [19, 18, 16],
         [17, 16, 14]],

        ...,

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]], dtype=uint8)]


In [87]:
ft = FunctionTransformer(flatten_array)

In [88]:
# make a column transformer
ct = make_column_transformer((ft, ["image_array"]))

In [89]:
ct.fit_transform(X_train)

ValueError: The output of the 'functiontransformer' transformer should be 2D (scipy matrix, array, or pandas DataFrame).

In [107]:
aaa = flatten_array(X_train)

TypeError: float() argument must be a string or a number, not 'builtin_function_or_method'

In [105]:
aaa[0]

array([6.91607027e-310])

In [19]:
# make pipeline of transformers and classifier
pipe = make_pipeline(ct, clf)

In [22]:
# train the classifier
pipe.fit(X_train, y_train)

ValueError: setting an array element with a sequence.

In [7]:
flatten_array(X[0])

array([144, 120,  82, ...,   0,   0,   0], dtype=uint8)

In [15]:
X.iloc[0].ravel()

array([144, 120,  82, ...,   0,   0,   0], dtype=uint8)

In [9]:
type(X_train[0])

numpy.ndarray

In [19]:
def flatten_array(arr):
    return arr.values.flatten()

In [20]:
aaa = pd.Series([1, 2, 3])
flatten_array(aaa)

array([1, 2, 3])

In [24]:
(ft.fit_transform(X_train)).shape

(7772,)

In [95]:
X_train.values.squeeze()[0:2]

array([array([[[190, 157, 140],
               [208, 177, 157],
               [206, 182, 158],
               ...,
               [  0,   0,   0],
               [  0,   0,   0],
               [  0,   0,   0]],

              [[207, 177, 166],
               [197, 169, 155],
               [182, 161, 142],
               ...,
               [  0,   0,   0],
               [  0,   0,   0],
               [  0,   0,   0]],

              [[188, 164, 162],
               [192, 171, 166],
               [191, 174, 164],
               ...,
               [  0,   0,   0],
               [  0,   0,   0],
               [  0,   0,   0]],

              ...,

              [[162, 145, 129],
               [164, 147, 129],
               [161, 143, 123],
               ...,
               [  0,   0,   0],
               [  0,   0,   0],
               [  0,   0,   0]],

              [[154, 132, 111],
               [153, 131, 108],
               [150, 126, 102],
               ...,
        

In [53]:
X_train.values[0].flatten()

array([190, 157, 140, ...,   0,   0,   0], dtype=uint8)

In [ ]:
lambda x: x.flatten